<?php

// This file was automatically generated by Cryptographp_XH.

$cryptwidth = 130;
$cryptheight = 40;
$bgR = 255;
$bgG = 255;
$bgB = 255;
$bgclear = true;
$bgimg = '';
$bgframe = true;
$charR = 0;
$charG = 0;
$charB = 0;
$charcolorrnd = true;
$charcolorrndlevel = 2;
$charclear = 0;
$tfont = array('luggerbu.ttf');
$charel = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
$crypteasy = true;
$charelc = 'BCDFGHJKLMNPQRSTVWXZ';
$charelv = 'AEIOUY';
$charnbmin = 4;
$charnbmax = 4;
$charspace = 20;
$charsizemin = 14;
$charsizemax = 16;
$charanglemax = 25;
$charup = true;
$cryptgaussianblur = false;
$cryptgrayscal = false;
$noisepxmin = 10;
$noisepxmax = 10;
$noiselinemin = 1;
$noiselinemax = 1;
$nbcirclemin = 1;
$nbcirclemax = 1;
$noisecolorchar = 3;
$brushsize = 3;
$noiseup = false;
$cryptformat = 'png';
$cryptusetimer = 0;
$cryptusertimererror = 3;
$cryptusemax = 100;
$cryptoneuse = true;

?>
