<?php

$plugin_cf['cryptographp']['crypt_width']="130";
$plugin_cf['cryptographp']['crypt_height']="40";
$plugin_cf['cryptographp']['bg_rgb_red']="255";
$plugin_cf['cryptographp']['bg_rgb_green']="255";
$plugin_cf['cryptographp']['bg_rgb_blue']="255";
$plugin_cf['cryptographp']['bg_clear']="yes";
$plugin_cf['cryptographp']['bg_image']="";
$plugin_cf['cryptographp']['bg_frame']="yes";
$plugin_cf['cryptographp']['char_rgb_red']="0";
$plugin_cf['cryptographp']['char_rgb_green']="0";
$plugin_cf['cryptographp']['char_rgb_blue']="0";
$plugin_cf['cryptographp']['char_color_random']="yes";
$plugin_cf['cryptographp']['char_color_random_level']="2";
$plugin_cf['cryptographp']['char_clear']="0";
$plugin_cf['cryptographp']['fonts']="luggerbu.ttf";
$plugin_cf['cryptographp']['char_allowed']="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
$plugin_cf['cryptographp']['crypt_easy']="yes";
$plugin_cf['cryptographp']['char_allowed_consonants']="BCDFGHJKLMNPQRSTVWXZ";
$plugin_cf['cryptographp']['char_allowed_vowels']="AEIOUY";
$plugin_cf['cryptographp']['char_count_min']="4";
$plugin_cf['cryptographp']['char_count_max']="4";
$plugin_cf['cryptographp']['char_space']="20";
$plugin_cf['cryptographp']['char_size_min']="14";
$plugin_cf['cryptographp']['char_size_max']="16";
$plugin_cf['cryptographp']['char_angle_max']="25";
$plugin_cf['cryptographp']['char_displace']="yes";
$plugin_cf['cryptographp']['crypt_gaussian_blur']="no";
$plugin_cf['cryptographp']['crypt_gray_scale']="no";
$plugin_cf['cryptographp']['noise_pixel_min']="500";
$plugin_cf['cryptographp']['noise_pixel_max']="500";
$plugin_cf['cryptographp']['noise_line_min']="1";
$plugin_cf['cryptographp']['noise_line_max']="1";
$plugin_cf['cryptographp']['noise_circle_min']="1";
$plugin_cf['cryptographp']['noise_circle_max']="1";
$plugin_cf['cryptographp']['noise_color_char']="3";
$plugin_cf['cryptographp']['noise_brush_size']="3";
$plugin_cf['cryptographp']['noise_above']="no";
$plugin_cf['cryptographp']['crypt_format']="png";
$plugin_cf['cryptographp']['crypt_use_timer']="0";
$plugin_cf['cryptographp']['crypt_use_timer_error']="yes";
$plugin_cf['cryptographp']['crypt_expiration']="600";

?>
