name: checks
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: composer
      - name: Install CMSimple_XH
        run: |
          curl -fsSL -o CMSimple_XH-1.7.5.zip https://github.com/cmsimple-xh/cmsimple-xh/releases/download/1.7.5/CMSimple_XH-1.7.5.zip
          unzip -q CMSimple_XH-1.7.5.zip
      - name: Checkout Cryptographp_XH
        uses: actions/checkout@v3
        with:
          path: 'cmsimplexh/plugins/cryptographp'
      - name: composer install
        run: cd cmsimplexh/plugins/cryptographp && composer install
      - name: phing sniff
        run: cd cmsimplexh/plugins/cryptographp && PATH=vendor/bin:$PATH phing sniff
      - name: phing stan
        run: cd cmsimplexh/plugins/cryptographp && PATH=vendor/bin:$PATH phing stan
      - name: phing test
        run: cd cmsimplexh/plugins/cryptographp && PATH=vendor/bin:$PATH FREETYPE_PROPERTIES=truetype:interpreter-version=35 phing test
      - name: Upload test failure images
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: cmsimplexh/plugins/cryptographp/tests/images/*.out.png
          if-no-files-found: ignore
